modules:
  - name
  - mana_cost
  - card_faces:
      - object
      - name
      - mana_cost
      - type_line
      - oracle_text
      - image_uris:
          - small
          - normal
      - power
      - toughness
  - type_line
  - oracle_text
  - power
  - toughness
  - legalities:
      - commander
      - modern
      - vintage
  - finishes
  - set_name
  - reprint
  - release_date
  - rarity
  - prices:
      - usd
      - usd_foil