options:
  formatting:
    indent_length: 2
  color:
    enabled: true
    set_key_color: 117
    set_val_color: 15

modules:
  - name
  - mana_cost
  - type_line
  - card_faces:
      - object
      - name
      - mana_cost
      - type_line
      - oracle_text
      - loyalty
      - power
      - toughness
  - oracle_text
  - loyalty
  - power
  - toughness
  - legalities:
      - commander
      - modern
      - standard
  - finishes
  - set_name
  - rarity
  - prices:
      - usd
      - usd_foil
